# Generated by Django 5.2.6 on 2025-09-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('US', 'United States'), ('UK', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('FR', 'France'), ('DE', 'Germany'), ('IN', 'India'), ('JP', 'Japan'), ('BR', 'Brazil'), ('MX', 'Mexico'), ('IT', 'Italy'), ('ES', 'Spain'), ('RU', 'Russia'), ('CN', 'China'), ('KR', 'South Korea'), ('SE', 'Sweden'), ('NL', 'Netherlands'), ('NO', 'Norway'), ('DK', 'Denmark'), ('FI', 'Finland')], max_length=2, null=True)),
            ],
        ),
    ]
