# Generated by Django 5.2.6 on 2025-10-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Br_release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
